# Directory where input plink filesets are.
# No trailing / is required.
directory: /sc/arion/projects/LOAD/shea/data/ADRC_CFI/plink

# Select chromosomes you want to upload
chr:
  from: 1
  to: 22
  chrlist: ~
    # use dashes here for list of others

# Location of fasta file for flipping and VCFcheck
ref:
  /sc/arion/projects/LOAD/shea/data/reference_panels/human_g1k_v37.fasta

# Subject and sample level QC thresholds
qc:
  hwe: 0.000001
  #Hardy-Weinberg Equilibrium Cutoff ("false" to skip)
  #MAF Cutoff ("false" to skip)
  maf: false
  #Variant level missingness cutoff
  geno: 0.05
  #Subject level missingness cutoff
  mind: 0.05

# Sample filtering

chr_callrate: False
chunk_callrate: True

# filename of samples to include (plink --keep)
include_samp:

# filename of samples to exclude (plink --remove)
exclude_samp:

# --keep accepts a space/tab-delimited text file with
# family IDs in the first column and within-family IDs
# in the second column, and removes all unlisted samples
# from the current analysis. --remove does the same for
# all listed samples.

check_vcf: False
checkEnv: checkVCF
